Traceback (most recent call last):
  File "train.py", line 241, in <module>
    main()
  File "train.py", line 176, in main
    gen_send_plot(epoch)
  File "train.py", line 210, in gen_send_plot
    plt.savefig("/Figures/training_loss_so_far.png")
  File "/home/seagie/miniconda3/lib/python3.8/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/seagie/miniconda3/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/seagie/miniconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/home/seagie/miniconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/seagie/miniconda3/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    mpl.image.imsave(
  File "/home/seagie/miniconda3/lib/python3.8/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/seagie/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/Figures/training_loss_so_far.png'
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    save_model_sum()
  File "train.py", line 231, in save_model_sum
    encoder.summary()
  File "/home/seagie/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2351, in summary
    raise ValueError('This model has not yet been built. '
ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.
